inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-sorted_methods_by_call

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 120

Gemspec/DevelopmentDependencies:
  Enabled: false

SortedMethodsByCall/Waterfall:
  Enabled: true
