module CodeGenerator
  class Generator
    @methods: untyped

    @class_methods: untyped

    def initialize: () -> void

    def self.new: () ?{ (?) -> untyped } -> untyped

    def build: () -> untyped

    def public_method: (untyped name) { (?) -> untyped } -> untyped

    def private_method: (untyped name) { (?) -> untyped } -> untyped

    def protected_method: (untyped name) { (?) -> untyped } -> untyped

    def public_class_method: (untyped name) { (?) -> untyped } -> untyped

    def private_class_method: (untyped name) { (?) -> untyped } -> untyped

    private

    attr_reader methods: untyped

    attr_reader class_methods: untyped

    def define_instance_methods: (untyped klass) -> (nil | untyped)

    def define_class_methods: (untyped klass) -> (nil | untyped)

    # lib/code_generator/generator.rb
    def define_method_with_params: (untyped target_class, untyped method_config, untyped define_method_name) -> untyped

    def calculate_return_value: (untyped method_config) -> untyped

    def generate_random_object: (untyped klass) -> untyped
  end
end
